- alias: night lights on
  trigger:
    platform: sun
    event: sunset
  action:
  - service: switch.turn_on
    entity_id: switch.lampada_lettura
  id: 7e66e6c032c645d2806966d455c12965

- alias: night lights off
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: switch.turn_off
    entity_id: switch.lampada_lettura
  id: b4a2b39e7fc845c09288da8393926bdc

- id: '1595670571853'
  alias: tts-power
  description: ''
  trigger:
  - platform: mqtt
    topic: ha/tts/google_translate_say
  condition: []
  action:
    - service: tts.google_translate_say
      data_template:
        entity_id: "{{ trigger.payload_json['speech']['entity_id'] }}"
        language: "{{ trigger.payload_json['speech']['language'] }}"
        message: "{{ trigger.payload_json['speech']['message'] }}"

- id: "boiler_timer_on_20200815"
  alias: boiler timer on
  description: ''
  trigger:
  - entity_id: switch.boiler
    for: 00:40:00
    platform: state
    to: 'on'
  action:
  - entity_id: switch.boiler
    service: switch.turn_off
- id: cong_temp_alarm_20200816
  alias: cong temp alarm
  description: controlla se la cella frigorifera non raffredda
  trigger:
  - platform: numeric_state
    entity_id: sensor.cong
    above: -9.0
  action:
  - service: tts.google_translate_say
    data_template:
      entity_id: media_player.entryway
      language: it
      message: Attenzione ! il congelatore è spento ed è in allarme
- id: morning_boiler_20200817
  alias: boiler on at morning
  description: accende il boiler al mattino presto
  trigger:
  - platform: time
    at: 07:00:00
  action:
  - service: switch.turn_on
    entity_id: switch.boiler
- id: '1597819488092'
  alias: ventola troppo caldo
  description: ''
  trigger:
  - entity_id: person.antonio
    platform: state
    to: home
  condition:
  - above: '27.3'
    condition: numeric_state
    entity_id: switch.termo_lab
  action:
  - data: {}
    entity_id: switch.vent
    service: switch.toggle
- id: boiler_proximity_20200819
  alias: boiler proximity
  description: ''
  trigger:
  - below: '1300'
    entity_id: proximity.home
    platform: numeric_state
  condition:
  - condition: template
    value_template: '{{ states.proximity.home.attributes.dir_of_travel == "towards"
      }}'
  action:
  - data: {}
    entity_id: switch.boiler
    service: switch.turn_on
  - data:
      message: stai arrivando a casa, accendo il boiler
    service: telegram_bot.send_message

- id: '1598130003086'
  alias: away home off
  description: ''
  trigger:
  - entity_id: person.antonio
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data: {}
    entity_id: switch.vent
    service: switch.turn_off
  - data: {}
    entity_id: switch.corridoio
    service: switch.turn_off
- id: away_home_on_20200824
  alias: away home on
  description: ''
  trigger:
  - below: '1000'
    entity_id: proximity.home
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.vent
    service: switch.turn_on
  - data: {}
    entity_id: switch.corridoio
    service: switch.turn_on
- id: '1603984670728'
  alias: luce cucina on
  description: ''
  trigger:
  - at: 08:00:00
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.vent
    service: switch.turn_on
- id: '1603984752481'
  alias: luce cucina off
  description: ''
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: switch.vent
    service: switch.turn_off
