
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# casa torino 2022
recorder:
    purge_keep_days: 90
    commit_interval: 60
    exclude:
        domains:
          - automation
          - updater
          - weblink
        entity_globs:
          - sensor.weather_*
        entities:
          - sun.sun # Don't record sun data
          - sensor.last_boot # Comes from 'systemmonitor' sensor platform
          - sensor.date
        event_types:
          - call_service # Don't record service calls

logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
    domains:
      - sun
      - weblink

mqtt:
  binary_sensor:
    - name: "PIR bagno"
      state_topic: "stat/tasmota_4685D8/PIR1"
      availability_topic: "tele/tasmota_4685D8/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"
      device_class: motion
  switch:
    - name: "boiler"
      state_topic: "stat/tasmota_67E683/RESULT"
      value_template: "{{ value_json.POWER }}"
      command_topic: "cmnd/tasmota_67E683/POWER"
      payload_on: "ON"
      payload_off: "OFF"
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
      qos: 1
      retain: false
  sensor:
    - name: "boiler kWh Day"
      state_topic: "tele/tasmota_67E683/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"
      expire_after: 45
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
#     device_class: energy
    - name: "boiler kWh Tot"
      state_topic: "tele/tasmota_67E683/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"
      expire_after: 45
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
#     state_class: total_increasing
#     device_class: energy
    - name: "boiler W"
      state_topic: "tele/tasmota_67E683/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"
      expire_after: 45
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
#     state_class: measurement
#     device_class: power
    - name: "boiler V"
      state_topic: "tele/tasmota_67E683/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"
      expire_after: 45
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
#     state_class: measurement
    - name: "boiler A"
      state_topic: "tele/tasmota_67E683/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"
      expire_after: 45
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
#     state_class: measurement
    - name: "boiler F"
      state_topic: "tele/tasmota_67E683/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Factor"] }}'
      unit_of_measurement: "F"
      expire_after: 45
      availability_topic: "tele/tasmota_67E683/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
#     state_class: measurement
    - name: "gr.frigo kWh Day"
      state_topic: "tele/tasmota_6835DF/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"
    - name: "gr.frigo kWh Tot"
      state_topic: "tele/tasmota_6835DF/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"
    - name: "gr.frigo W"
      state_topic: "tele/tasmota_6835DF/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"
    - name: "gr.frigo V"
      state_topic: "tele/tasmota_6835DF/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"
    - name: "gr.frigo A"
      state_topic: "tele/tasmota_6835DF/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"
    - name: "gr.frigo F"
      state_topic: "tele/tasmota_6835DF/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Factor"] }}'
      unit_of_measurement: "F"
    - name: "gr.piastra kWh Day"
      state_topic: "tele/tasmota_3D5CA8/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"
    - name: "gr.piastra kWh Tot"
      state_topic: "tele/tasmota_3D5CA8/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"
    - name: "gr.piastra W"
      state_topic: "tele/tasmota_3D5CA8/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"
    - name: "gr.piastra V"
      state_topic: "tele/tasmota_3D5CA8/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"
    - name: "gr.piastra A"
      state_topic: "tele/tasmota_3D5CA8/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"
    - name: "gr.piastra F"
      state_topic: "tele/tasmota_3D5CA8/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Factor"] }}'
      unit_of_measurement: "F"
    - name: "microwav kWh Day"
      state_topic: "tele/tasmota_67EAC1/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Today"] }}'
      unit_of_measurement: "kWh"
    - name: "microwav kWh Tot"
      state_topic: "tele/tasmota_67EAC1/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Total"] }}'
      unit_of_measurement: "kWh"
    - name: "microwav W"
      state_topic: "tele/tasmota_67EAC1/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Power"] }}'
      unit_of_measurement: "W"
    - name: "microwav V"
      state_topic: "tele/tasmota_67EAC1/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Voltage"] }}'
      unit_of_measurement: "V"
    - name: "microwav A"
      state_topic: "tele/tasmota_67EAC1/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Current"] }}'
      unit_of_measurement: "A"
    - name: "microwav F"
      state_topic: "tele/tasmota_67EAC1/SENSOR"
      value_template: '{{ value_json["ENERGY"]["Factor"] }}'
      unit_of_measurement: "F"

#
# calculated sensors
#
sensor:
  - platform: template
    sensors:
      total_watt:
        friendly_name: "total W"
        unit_of_measurement: "W"
        value_template: >
             {{ (states('sensor.powr2_20220206_energy_power') | float(0) +
                 states('sensor.powr3_20221221_energy_power') | float(0) +
                 states('sensor.microwav_w') | float(0) +
                 states('sensor.boiler_w') | float(0) +
                 states('sensor.gr_frigo_w') | float(0) +
                 states('sensor.gr_piastra_w') | float(0)) | 
              round | int }}
      home_lux_low_range:
        friendly_name: "home lux low range"
        unit_of_measurement: "lx"
        value_template: >
            {% if (states('sensor.home_lux_tsl2561_illuminance') | float(0)) > 5000 %}
                5000.0
            {% else %}
                {{ states('sensor.home_lux_tsl2561_illuminance') | float(0) }}
            {% endif %}

#
# esterno on NUC docker and static ip
#
media_player:
  - platform: mpd
    host: 192.168.147.2
    port: 6600
    name: "mopidy"
    scan_interval: 1

#
# Text to speech
#
tts:
#  - platform: google_translate
  - platform: picotts
    language: "it-IT"

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
